# Generated by Django 6.0.2 on 2026-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='icon_path',
            field=models.TextField(default='default.png'),
            preserve_default=False,
        ),
    ]
