# Generated by Django 6.0.2 on 2026-02-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_icon_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='category_id',
        ),
    ]
