# Generated by Django 6.0.2 on 2026-02-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_category_id_game_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='category_id',
        ),
    ]
