# Generated by Django 6.0.2 on 2026-02-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_category_game_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category_id',
            new_name='category',
        ),
    ]
