# Generated by Django 6.0.2 on 2026-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_category_id_game_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='icon_path',
        ),
        migrations.AddField(
            model_name='game',
            name='icon_url',
            field=models.URLField(default='https://www.pexels.com/search/nature/'),
            preserve_default=False,
        ),
    ]
