# Generated by Django 6.0.2 on 2026-02-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
    ]
