# Generated by Django 6.0.2 on 2026-02-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_game_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='added_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
