# Generated by Django 6.0.2 on 2026-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_game_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameplay_video',
            field=models.FileField(blank=True, null=True, upload_to='game_videos/'),
        ),
    ]
