# Generated by Django 6.0.2 on 2026-02-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_game_gameplay_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
